### ISSUE TITLE
Can't get the exact duration of the file

### ISSUE THREAD

**Issue by wojciechgizynski** [caprica/vlcj-info#4]
I'm trying to get the exact duration of the media file. This is the code I wrote:
```
Section video = mediaInfo.first("Video");

System.out.println(video.value("Frame rate"));
System.out.println(video.value("Duration"));
System.out.println(video.duration("Duration"));
```
And here's the output:
```
23.976 (24000/1001) FPS
2 h 20 min
null
```
I was following the example from [the file in the repo](https://github.com/caprica/vlcj-info/blob/master/src/test/java/uk/co/caprica/vlcjinfo/VlcjInfoTest.java). I don't understand why Duration hasn't been found in Video section, when `video.value("Duration")` works just fine. Any help?

**Comment by caprica** [comment]
This is happening because the regular expression used to match the duration value is not matching "2 h 20 min".

There are two problems with the regexp:

1. I think there's a typo that has crept in
2. it expects a format like "2h 20m" not "2 h 20 min"

I thought that duration format was fixed, maybe something has changed in a new MediaInfo version.

Anyway, thanks for the report, I'll push a fix as soon as I have some time.

**Comment by wojciechgizynski** [comment]
Thanks for the quick response. But I still have some concerns:

First, I've tried getting `video.decimal("Frame rate")` and while it's working for `25.000 FPS`, it doesn't for the file I mentioned before. Meaning that I get `null` for `23.976 (24000/1001) FPS`.

Second, I need the exact duration of the media file. So `2 h 20 min` doesn't do it for me. I need seconds and miliseconds. Something like this `02:20:31.565`. Is it doable with vlcj-info? Looking for information, I came across [this answer on stackoverflow](https://stackoverflow.com/a/23456638/1113501). It seems that executing 
```
mediainfo --Inform="Video;%Duration/String3%" example.mp4
``` 
might do the trick. I haven't tried that myself, I only use MediaInfo via vlcj-info and don't even have the executable file. What are your thoughts?

**Comment by caprica** [comment]
This library uses libmediainfo rather than mediainfo itself, the API is a bit different.

Indeed it looks like the API is not returning a number of milliseconds.

I can maybe look into this a bit more over the next week or so.

It's been so long since I wrote this I don't recall everything about it just yet.

**Comment by wojciechgizynski** [comment]
Thank you, I appreciate the effort.

**Comment by caprica** [comment]
So after having researched this a bit, the native API is kinda messy.

From what I can tell the raw native "inform" API is a bulk API that returns strings with a default formatting.

If you want to choose a different formatting I could only find a way to do that by querying individual pieces of information - and that API was not available in this library.

To resolve this, I added a new `MediaInfoFile` API. It uses the same string formatting as in the example you posted above.

Since there are so many different formatting strings, parsing of these strings into a usable value is being punted to the application developer rather than being done in this library.

Further details in the Javadoc, once it's published.

A new release is on its way to Maven Central today.

**Comment by wojciechgizynski** [comment]
Works great, thank you!
